[[redirects]]
  from = "/api/*"
  to = "https://youssef-friender.onrender.com/:splat"
  status = 200
  headers = { X-From = "Netlify" }
  force = true

[[redirects]]
  from = “/*”
  to = “/index.html”
  status = 200